name: Docker Image Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect mybuilder --bootstrap

      - name: Build Docker image
        run: |
          docker buildx build \
            --file ./Dockerfile \
            --platform linux/amd64 \
            --output type=image,oci-mediatypes=true \
            --tag my-image:latest \
            .

      - name: Save Docker image
        run: |
          docker save -o my-image.tar my-image:latest
          echo "::set-output name=docker_image::my-image.tar"

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: my-image.tar
